# Generated by Django 3.1.5 on 2021-01-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Vet visit date')),
                ('visit', models.CharField(choices=[('A', 'Adult Vaccines'), ('P', 'Puppy Vaccines')], default='A', max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dog')),
            ],
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
